language: shell

sudo: required

services:
- docker

before_install:
- docker pull gcr.io/gcp-dplearn/dplearn:latest-app
- docker pull gcr.io/gcp-dplearn/dplearn:latest-python3-cpu

script:
- ./scripts/docker/test-app.sh
- ./scripts/docker/test-python3-cpu.sh
