language: shell

sudo: required

services:
- docker

before_install:
- ./scripts/docker/build-app.sh
- ./scripts/docker/build-python3-cpu.sh

script:
- ./scripts/docker/test-app.sh
- ./scripts/docker/test-python3-cpu.sh
