steps:
- name: gcr.io/cloud-builders/docker
  args:
  - build
  - --tag
  - gcr.io/gcp-dplearn/dplearn:latest-gpu
  - --file
  - ./dockerfiles/gpu/Dockerfile
  - .
- name: gcr.io/cloud-builders/docker
  args:
  - build
  - --tag
  - gcr.io/gcp-dplearn/dplearn:latest-cpu
  - --file
  - ./dockerfiles/cpu/Dockerfile
  - .
images:
- gcr.io/gcp-dplearn/dplearn:latest-gpu
- gcr.io/gcp-dplearn/dplearn:latest-cpu

# TODO: configure timeouts
