[[constraint]]
  name = "github.com/coreos/etcd"
  revision = "a40cdc7baa333e230098ee3de5d4d36b31716dda"

[[constraint]]
  name = "github.com/dustin/go-humanize"
  revision = "259d2a102b871d17f30e3cd9881a642961a1e486"

[[constraint]]
  name = "github.com/golang/glog"
  revision = "23def4e6c14b4da8ac2ed8007337bc5eb5007998"

[[constraint]]
  name = "github.com/petar/GoLLRB"
  revision = "53be0d36a84c2a886ca057d34b6aa4468df9ccb4"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  revision = "cd8b52f8269e0feb286dfeef29f8fe4d5b397e0b"

[[constraint]]
  name = "github.com/gyuho/archiver"
  revision = "9498f426722d1e0f1c4d5801b282ba7a8720f717"

[[constraint]]
  name = "golang.org/x/sys"
  revision = "0b25a408a50076fbbcae6b7ac0ea5fbb0b085e79"

[[constraint]]
  name = "golang.org/x/oauth2"
  revision = "f047394b6d14284165300fd82dad67edb3a4d7f6"

[[constraint]]
  name = "cloud.google.com/go"
  revision = "69931d826ffbbcb4f8451b42d5cf7fc2ac6c7443"

[[constraint]]
  name = "google.golang.org/api"
  revision = "1faa39f42f12a54fa82ca5902a7ab642d5b09ad1"

[[constraint]]
  name = "google.golang.org/appengine"
  revision = "a2f4131514e563cedfdb6e7d267df9ad48591e93"
