################################
# Direct dependencies

# https://github.com/coreos/etcd
[[constraint]]
  name = "github.com/coreos/etcd"
  revision = "44e1f6f019a98dbea4c8c8def5f077fb0dd83e8a"

# https://github.com/dustin/go-humanize
[[constraint]]
  name = "github.com/dustin/go-humanize"
  revision = "bb3d318650d48840a39aa21a027c6630e198e626"

# https://github.com/golang/glog
[[constraint]]
  name = "github.com/golang/glog"
  revision = "23def4e6c14b4da8ac2ed8007337bc5eb5007998"

# https://github.com/go-yaml/yaml
[[constraint]]
  name = "gopkg.in/yaml.v2"
  revision = "287cf08546ab5e7e37d55a84f7ed3fd1db036de5"

# https://github.com/gyuho/archiver
[[constraint]]
  name = "github.com/gyuho/archiver"
  revision = "0c5460b3c28c626130e2efec2c651226384234e9"

# https://github.com/golang/oauth2
[[constraint]]
  name = "golang.org/x/oauth2"
  revision = "30785a2c434e431ef7c507b54617d6a951d5f2b4"

# https://github.com/google/google-api-go-client
[[constraint]]
  name = "google.golang.org/api"
  revision = "e5c227fa33ebccc5a430d863efae400431fc0e85"

# https://github.com/golang/appengine
[[constraint]]
  name = "google.golang.org/appengine"
  revision = "5bee14b453b4c71be47ec1781b0fa61c2ea182db"

# https://github.com/GoogleCloudPlatform/google-cloud-go
[[constraint]]
  name = "cloud.google.com/go"
  revision = "2a6493c7a9214bf56c1003bd97443d505cc7e952"
################################

################################
# Transitive dependencies, but to override

# https://github.com/coreos/bbolt
[[override]]
  name = "github.com/coreos/bbolt"
  version = "v1.3.1-coreos.6"

# https://github.com/grpc/grpc-go
[[override]]
  name = "google.golang.org/grpc"
  source = "https://github.com/grpc/grpc-go.git"
  version = "v1.7.5"

# https://github.com/grpc-ecosystem/grpc-gateway
[[override]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  version = "v1.3.0"
################################
