# https://github.com/coreos/etcd
[[constraint]]
  name = "github.com/coreos/etcd"
  revision = "15bfc1b36162805e8a90ae747d955667870c2f95"

# https://github.com/coreos/bbolt
[[override]]
  name = "github.com/coreos/bbolt"
  version = "v1.3.1-coreos.5"

# https://github.com/dustin/go-humanize
[[constraint]]
  name = "github.com/dustin/go-humanize"
  revision = "bb3d318650d48840a39aa21a027c6630e198e626"

# https://github.com/golang/glog
[[constraint]]
  name = "github.com/golang/glog"
  revision = "23def4e6c14b4da8ac2ed8007337bc5eb5007998"

# https://github.com/petar/GoLLRB
[[constraint]]
  name = "github.com/petar/GoLLRB"
  revision = "53be0d36a84c2a886ca057d34b6aa4468df9ccb4"

# https://github.com/go-yaml/yaml
[[constraint]]
  name = "gopkg.in/yaml.v2"
  revision = "cd8b52f8269e0feb286dfeef29f8fe4d5b397e0b"

# https://github.com/gyuho/archiver
[[constraint]]
  name = "github.com/gyuho/archiver"
  revision = "6348b67ad5721f102e9645f5051121af225aba8c"

# https://github.com/golang/sys
[[constraint]]
  name = "golang.org/x/sys"
  revision = "1e2299c37cc91a509f1b12369872d27be0ce98a6"

# https://github.com/golang/net
[[constraint]]
  name = "golang.org/x/net"
  revision = "a337091b0525af65de94df2eb7e98bd9962dcbe2"

# https://github.com/golang/oauth2
[[constraint]]
  name = "golang.org/x/oauth2"
  revision = "9ff8ebcc8e241d46f52ecc5bff0e5a2f2dbef402"

# https://github.com/google/google-api-go-client
[[constraint]]
  name = "google.golang.org/api"
  revision = "a0c31fb0028e0111b942a29b9fc2e9235202c48b"

# https://github.com/golang/appengine
[[constraint]]
  name = "google.golang.org/appengine"
  revision = "9d8544a6b2c7df9cff240fcf92d7b2f59bc13416"

# https://github.com/GoogleCloudPlatform/google-cloud-go
[[constraint]]
  name = "cloud.google.com/go"
  revision = "b42e7d1aac8a4c07a3109dd54bbca4abc3f005ea"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.7.3"

# github.com/grpc-ecosystem/grpc-gateway
[[constraint]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  version = "v1.3.0"
