# https://github.com/coreos/etcd
[[constraint]]
  name = "github.com/coreos/etcd"
  revision = "608df0fc90f0d775ee482dd891bc1f3e96c35d81"

# https://github.com/coreos/bbolt
[[constraint]]
  name = "github.com/coreos/bbolt"
  revision = "ad39960eb40bb33c9bda31bed2eaf4fdda15efe6"
  source = "github.com/coreos/bbolt"

# https://github.com/dustin/go-humanize
[[constraint]]
  name = "github.com/dustin/go-humanize"
  revision = "259d2a102b871d17f30e3cd9881a642961a1e486"

# https://github.com/golang/glog
[[constraint]]
  name = "github.com/golang/glog"
  revision = "23def4e6c14b4da8ac2ed8007337bc5eb5007998"

# https://github.com/petar/GoLLRB
[[constraint]]
  name = "github.com/petar/GoLLRB"
  revision = "53be0d36a84c2a886ca057d34b6aa4468df9ccb4"

# https://github.com/go-yaml/yaml
[[constraint]]
  name = "gopkg.in/yaml.v2"
  revision = "cd8b52f8269e0feb286dfeef29f8fe4d5b397e0b"

# https://github.com/gyuho/archiver
[[constraint]]
  name = "github.com/gyuho/archiver"
  revision = "9498f426722d1e0f1c4d5801b282ba7a8720f717"

# https://github.com/golang/sys
[[constraint]]
  name = "golang.org/x/sys"
  revision = "4cd6d1a821c7175768725b55ca82f14683a29ea4"

# https://github.com/golang/net
[[constraint]]
  name = "golang.org/x/net"
  revision = "f01ecb60fe3835d80d9a0b7b2bf24b228c89260e"

# https://github.com/golang/oauth2
[[constraint]]
  name = "golang.org/x/oauth2"
  revision = "cce311a261e6fcf29de72ca96827bdb0b7d9c9e6"

# https://github.com/google/google-api-go-client
[[constraint]]
  name = "google.golang.org/api"
  revision = "e665075b5ff79143ba49c58fab02df9dc122afd5"

# https://github.com/golang/appengine
[[constraint]]
  name = "google.golang.org/appengine"
  revision = "ad2570cd3913654e00c5f0183b39d2f998e54046"

# https://github.com/GoogleCloudPlatform/google-cloud-go
[[constraint]]
  name = "cloud.google.com/go"
  revision = "3e1507a0d90d17e4fdd8ef75e8f037ebecc854ba"
